- project:
    default-branch: main
    merge-mode: squash-merge
    check:
      jobs:
        - tox-linters:
            required-projects: zuul/zuul-jobs
    gate:
      jobs:
        - tox-linters:
            required-projects: zuul/zuul-jobs
