- job:
    name: gl-jobs-linters
    parent: tox
    description: |
      This job runs against base-jobs, project-config, openstack-zuul-jobs
      and zuul-jobs so we can properly lint our ansible playbooks / roles.
    required-projects:
      - opentelekomcloud-infra/otc-zuul-jobs
      - zuul/zuul-jobs
    vars:
      tox_envlist: linters
      tox_environment:
        ANSIBLE_ROLES_PATH: ~/src/opendev.org/zuul/zuul-jobs/roles:~/src/github.com/opentelekomcloud-infra/otc-zuul-jobs/roles:~/src/github.com/opentelekomcloud-infra/gl-project-config/roles:roles

- project:
    default-branch: main
    merge-mode: squash-merge
    check:
      jobs:
        - gl-jobs-linters
    gate:
      jobs:
        - gl-jobs-linters
