- project:
    default-branch: main
    merge-mode: squash-merge
    check:
      jobs:
        - otc-tox-linters:
            required-projects:
              - opentelekomcloud-infra/otc-zuul-jobs
              - zuul/zuul-jobs
    gate:
      jobs:
        - otc-tox-linters:
            required-projects:
              - opentelekomcloud-infra/otc-zuul-jobs
              - zuul/zuul-jobs


